### ISSUE TITLE
Extension is broken with v2 IsThereAnyDeal API and site redesign

### ISSUE THREAD

**Issue by bburky** [bburky/isthereanydeal-playnite#3]
The `/collection/import/` API is gone entirely:
https://github.com/IsThereAnyDeal/API/blob/master/migration.md#v01collectionimport

Need to rewrite import entirely and use the new API endpoints. Will likely require authenticated API access. New API is a REST API, this extension will likely need a UI implemented, will not be able to reuse the IsThereAnyDeal website UI in a browser window anymore.

**Comment by spineduke** [comment]
Hello! I'm pleasantly surprised that you're still maintaining this many years on. Was gonna report as much. Thank you for all the efforts!

**Comment by r6d2** [comment]
> New API is a REST API, this extension will likely need a UI implemented, will not be able to reuse the IsThereAnyDeal website UI in a browser window anymore.

Seems to be a lot more effort than with the previous version. I hope you get the time to fix it. Thanks for your great work on this!

**Comment by bburky** [comment]
Fixed! This extension has been entirely rewritten to handle the ITAD site redesign.

Let me know if anyone has any issues with the new version.
